<!doctype html>
<html lang="<?= $this->getLanguage(); ?>">
<head>
    <meta charset="<?= $this->getCharset(); ?>">
    <title><?= $this->getTitle(); ?></title>
    <base href="<?= $this->getBaseUrl() ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="assets/default/css/normalize.min.css">
    <link rel="stylesheet" href="assets/default/css/style.css">
</head>
<body>
    <?php $this->getBody(); ?>
</body>
</html>