<?= $message ?>
<div>
    <form action="/login" method="post">
        <label for="login">Login</label>
        <input type="text" name="login" id="login" value="<?= $login ?>">

        <br><br>

        <label for="pass">Senha</label>
        <input type="password" name="senha" id="senha" value="<?= $senha ?>">

        <hr>

        <input type="submit" name="action" value="Entrar">
    </form>
</div>